export const API_SAVE_LEVEL_FEE='API_SAVE_LEVEL_FEE';
export const API_GET_LEVEL_FEE='API_SAVE_LEVEL_FEE';
export const API_CREATE_LEVEL_FEE='API_CREATE_LEVEL_FEE';
export const API_DEL_LEVEL_FEE='API_DEL_LEVEL_FEE';
export const API_DEL_LEVEL_FEES='API_DEL_LEVEL_FEES';
export const GRID_COLLECT_LEVEL_FEE='GRID_PAGE_LEVEL_FEE';
export const GRID_CONF_LEVEL_FEE='GRID_CONF_LEVEL_FEE';
export const CHANGE_STATE='CHANGE_STATE';
